trainer: energy

dataset:
  train:
    src: /home/xin/fy/three/equiformer-master_three/datasets/oc20/train-26745/train/data.lmdb
    normalize_labels: True
    target_mean: -1.525913953781128
    target_std: 2.279365062713623
  val:
    src: /home/xin/fy/three/equiformer-master_three/datasets/oc20/train-26745/val_id/data.lmdb
  test:
    src: /home/xin/fy/three/equiformer-master_three/datasets/oc20/train-26745/test_id/data.lmdb
logger: tensorboard

task:
  dataset: single_point_lmdb
  description: "Relaxed state energy prediction from initial structure."
  type: regression
  metric: mae
  labels:
    - relaxed energy
